### ISSUE TITLE
Python integration does not work on SPSS modeler 18.1

### ISSUE THREAD

**Issue by ZackCode** [IBMPredictiveAnalytics/K_Means_with_MLlib#4]
Hi, I am trying  to get python integration working with SPSS modeler. However it seems SPSS cannot find my Python. I installed python in this path: "C:/ProgramData/Anaconda2", it is an anaconda install and has spark. I edited the `eas_pyspark_python_path` as suggested in this repo. Any extension using python just gives me messsage `cannot get data model: null`. Please advice. @niallmcc @Wenpei 

Thanks

**Comment by Wenpei** [comment]
ensure you have correct path, and .... change default option.cfg 's quota of `eas_pyspark_python_path` to right one

take a try, and good luck.
